// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbVGQxswwyTsfMYQDG4x_08_0RW2PNBLo',
    appId: '1:830705956189:web:84ffbde5945fc6acd2e4b4',
    messagingSenderId: '830705956189',
    projectId: 'gestion-salud-b1e02',
    authDomain: 'gestion-salud-b1e02.firebaseapp.com',
    storageBucket: 'gestion-salud-b1e02.firebasestorage.app',
    measurementId: 'G-X273BPEHGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv41V7VfmJwMF3UZXEk1b9GecJUrSpnfw',
    appId: '1:830705956189:android:37ba06cca5e0ae10d2e4b4',
    messagingSenderId: '830705956189',
    projectId: 'gestion-salud-b1e02',
    storageBucket: 'gestion-salud-b1e02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSwAVV_1y2Nexgsu9rVokAMTVToK64-Fo',
    appId: '1:830705956189:ios:66cff0f5bc7f87fbd2e4b4',
    messagingSenderId: '830705956189',
    projectId: 'gestion-salud-b1e02',
    storageBucket: 'gestion-salud-b1e02.firebasestorage.app',
    iosBundleId: 'com.example.gestionSalud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSwAVV_1y2Nexgsu9rVokAMTVToK64-Fo',
    appId: '1:830705956189:ios:66cff0f5bc7f87fbd2e4b4',
    messagingSenderId: '830705956189',
    projectId: 'gestion-salud-b1e02',
    storageBucket: 'gestion-salud-b1e02.firebasestorage.app',
    iosBundleId: 'com.example.gestionSalud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbVGQxswwyTsfMYQDG4x_08_0RW2PNBLo',
    appId: '1:830705956189:web:7226c576ff908b9ad2e4b4',
    messagingSenderId: '830705956189',
    projectId: 'gestion-salud-b1e02',
    authDomain: 'gestion-salud-b1e02.firebaseapp.com',
    storageBucket: 'gestion-salud-b1e02.firebasestorage.app',
    measurementId: 'G-X4CLZYV4NG',
  );

}